import type { Metadata } from "next";
import { ToastProvider } from "@/components/Toast";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="h-screen flex flex-col">
        <ToastProvider>{children}</ToastProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
